### ISSUE TITLE
Links to resources

### ISSUE THREAD

**Issue by emiliom** [ioos/bio_data_guide#12]
- The link at the top of the repo, https://marinebon.github.io/ioos_bio_data_scripts/, is broken. I'm guessing it's from the former repo location, and I'm also guessing that it should be replaced with https://ioos.github.io/bio_data_guide/
- Add some links on the README.md to relevant resources, both IOOS and others? My first suggestion: https://ioos.github.io/BioData-Training-Workshop/ Yeah, I could submit a PR to add this, but since it's not possible -- I think -- to submit a PR to update the top link, an issue covered both suggestions.

**Comment by 7yl4r** [comment]
I don't have permissions to remove the link at the top, @mwengren : will you remove that link for us please?

I added a link section with your suggested link and a couple others.

**Comment by emiliom** [comment]
Thanks!

BTW, you added a link to https://github.com/marinebon/bio_data_scripts_ioos_workshop_2019. But isn't basically the deprecated predecessor to this new repo?

**Comment by 7yl4r** [comment]
The plan right now is to clean most of the things there out of this repo and use this one as a more general landing page.
We did it this way instead of creating a new general one so that we could preserve the issues and discussions on this github repo.

So you are right that it is currently a deprecated predecessor, but I will be cleaning out many files from this repo soon and that link will be the only remaining place to get them easily.

**Comment by emiliom** [comment]
Ah, got it. Thanks for your work on this!

**Comment by mwengren** [comment]
Ok, I update the repo link to the correct location.  Should be all set.
