### ISSUE TITLE
Resolution of coordinates for transects and quadrats

### ISSUE THREAD

**Issue by mlonneman** [ioos/bio_data_guide#34]
For most protocols, MarineGEO collects two sets of coordinates: the beginning and end of a transect. I'm curious what, if any, processing will be necessary for providing the decimalLatitude and decimalLongitude values for transect and quadrat event observations in our event core tables. 

1. For a line, such as a transect, should decimalLatitude and decimalLongitude represent the centerpoint? Because "coordinateUncertaintyInMeters" is the radius of the smallest circle encompassing the entire feature, I assume this is the case. Either way, I'm planning on including a WKT footprint based on the beginning and end coordinates along with the lat/long values.

2. Do we need to calculate an estimated decimalLatitude and decimalLongitude for quadrats or is providing the coordinates at the transect level enough?

**Comment by albenson-usgs** [comment]
In general, we want to represent the data as closely as possible to how it was collected without creating new information that wasn't part of the original data collection. In this instance though where decimalLatitude and decimalLongitude are required, yes using the midpoint of the transect would make the most sense and then making sure the coordinateUncertaintyInMeters includes the radius of the transect + the uncertainty of the location estimation (GPS tends to be 30m). I'm glad you'll provide footprintWKT and in the georeferenceRemarks you might include a short note that this method was employed for the lat/lon.

No, I wouldn't calculate an estimated decimalLatitude and decimalLongitude for quadrats since this information was not collected when the data were collected.

**Comment by mlonneman** [comment]
Thanks Abby!
