### ISSUE TITLE
Change repository name?

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/bio_data_guide#67]
Is `bio_data_guide` still appropriate? Per our conversation last month, the scope of this repo is strictly standardizing to DwC? 

If that's true, should we change the repo name to `dwc_bio_data_guide` to reduce confusion?

**Comment by albenson-usgs** [comment]
Yes it's ok from my perspective to make this change.

**Comment by MathewBiddle** [comment]
Not sure if folks have referenced this, but changing the repo name might be troublesome. I forgot that the url for the book will change if we change the repo name. If we change the name to the proposed `dwc_bio_data_guide` the book url becomes `https://ioos.github.io/dwc_bio_data_guide/intro.html`

There are workarounds, like we did for migrating [notebooks_demos](https://github.com/ioos/ioos_code_lab) to [ioos_code_lab](https://github.com/ioos/ioos_code_lab). We made a copy of the repo and forwarded the notebooks_demos to the new site 
![image](https://user-images.githubusercontent.com/8480023/142072949-557394df-461b-43e2-9d2f-a126add6a804.png)

Just want to weigh our options and make sure this is the right move.

Also, maybe `dwc_data_guide` would be more simple...

**Comment by albenson-usgs** [comment]
Ok I guess after you bring the CodeLab example I've changed my mind a bit :-) I actually find it difficult to find the IOOS CodeLab and often end up at the previous location and then still have trouble getting to the new location. I feel that given this and unless someone is itching to use /ioos/bio_data_guide for their own purposes that instead of renaming the repo we change the wording in the documentation to make it clear it's focuses on Darwin Core. 

For example on the front page change the first header from Bio Data Guide to Darwin Core Guide but not change the url that will get you there.

**Comment by MathewBiddle** [comment]
![image](https://user-images.githubusercontent.com/8480023/142497133-fcdde7f4-57bc-42f8-be93-60cdf33dc71d.png)
