### ISSUE TITLE
`nan` `eventDate`s in AK salmon data - is `nan` a valid `eventDate` for an occurrence?

### ISSUE THREAD

**Issue by 7yl4r** [ioos/bio_data_guide#69]
The [new AK salmon dataset](https://obis.org/dataset/24e96d02-8909-4431-bc61-8cf8eadc9b7a) mentioned today is showing with some nan values for `eventDate` in the occurrence file.

Is that correct? How can an occurence row have no `eventDate`?

The jupyter notebook I used to load the data from the IPT is [here](https://github.com/USF-IMARS/obis_notebooks/blob/master/dwc_download_and_analyze.ipynb). 

The start/end dates look good but there are 66 rows at the beginning that are showing as `nan`.

**Comment by timvdstap** [comment]
Hey Tylar, there shouldn't be any nan values for `eventDate` in the **occurrence** file.. There are some rows in the event file that don't have an associated `eventDate`, and that's because the trawl is nested, following the hierarchy project-cruise-station-trawl, with eventDates linked to the trawl event. But occurrence records should always link back to an `eventID` that has an associated `eventDate` (and, looking at the occurrence file, this seems to be the case?) We chose this hierarchy as there will also be other data types collected at each station.
